project:
  type: website
  output-dir: _site

website:
  title: ""
  site-url: https://oxford-ihtm.io/open-reproducible-science/
  navbar:
    title: ""
    background: info
    logo: images/ihealth_base_inline.png
    logo-alt: Oxford iHealth
    tools:
      - icon: github
        href: https://github.com/OxfordIHTM/open-reproducible-science
    left:
      - href: https://oxford-ihtm.io/
        text: Home
      - text: Stories
        href: https://oxford-ihtm.io/stories.html
      - text: Teaching
        menu:
          - href: index.qmd
            text: Open and Reproducible Science in R
          - href: https://oxford-ihtm.io/teaching/learning-resources.qmd
            text: Learning Resources
      - href: projects/index.qmd
        text: Projects
  # sidebar:
  #   logo: images/ihealth_base_pos.png
  #   logo-alt: Oxford iHealth
  page-footer: 
    center: "Copyright 2024, University of Oxford MSc in International Health and Tropical Medicine" 
    background: light
    border: false
  reader-mode: true
  repo-url: https://github.com/OxfordIHTM/oxfordihtm.github.io
  repo-actions: [edit, issue]
  issue-url: https://github.com/OxfordIHTM/OxfordIHTM.github.io/issues
  cookie-consent:
    type: express
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-PSJXMNM72F"
    anonymize-ip: true
  
format:
  html:
    theme: journal
    css: styles.css
    toc: true
