---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Oxford International Health and Tropic Medicine Lecture Series on Open Science and Reproducible Research in R

<!-- badges: start -->
<!-- badges: end -->

Open Science is the practice of science in such a way that others can collaborate and contribute, where research data, lab notes and other research processes are freely available, under terms that enable reuse, redistribution and reproduction of the research and its underlying data and methods. Reproducible research means that research data and code are made available so that others are able to reach the same results as are claimed in scientific outputs. Closely related is the concept of replicability, the act of repeating a scientific methodology to reach similar conclusions. These concepts are core elements of empirical research.

This 6-part lecture series is designed to give Oxford IHTM students a foundational understanding and appreciation of the pillars of Open Science more broadly and within that the concepts, methods and tools for Reproducible Research more specifically. To further the students' learning, practical examples and exercises will be discussed and walked through using the R language for statistical computing as a way to practically demonstrate these concepts.

## Session 1: Open Science and Reproducible Research in R: An Overview

In this session, an overview of the what, why, and how of Open Science and Reproducible Research will be discussed to provide the learners with foundational understanding and appreciation of these concepts and their applications.

### Further  Reading    

Rick, Jessica & Alston, Jesse. (2020). A beginner’s guide to conducting reproducible research in ecology, evolution, and conservation. 10.32942/osf.io/h5r6n. 

### Teaching Material

Slides can be viewed at https://oxfordihtm.github.io/open-reproducible-science/session1.html

PDF version of slides can be downloaded at https://oxfordihtm.github.io/open-reproducible-science/pdf/session1-open-reproducible-science.pdf

R scripts for slides available [here](https://github.com/OxfordIHTM/open-reproducible-science/blob/a0a2d152e62a06a9cab6995f219018e3c0aafc91/session1.Rmd)

## Session 2: Git and GitHub for use with R: tools for versioning and sharing research

In this session, an overview of git and GitHub will be discussed along with their integration with R using RStudio. This wil then be followed by a practical session to guide learners on setting up git and GitHub onto their personal machines culminating in the learners accessing their first assignment in GitHub Classroom.

### Further Reading

Happy Git and GitHub for the useR - https://happygitwithr.com/

Perez-Riverol, Y., Gatto, L., Wang, R., Sachsenberg, T., Uszkoreit, J., Leprevost, F., Fufezan, C., Ternent, T., Eglen, S. J., Katz, D. S., Pollard, T. J., Konovalov, A., Flight, R. M., Blin, K., & Vizcaíno, J. A. (2016). Ten Simple Rules for Taking Advantage of Git and GitHub. PLoS computational biology, 12(7), e1004947. https://doi.org/10.1371/journal.pcbi.1004947

Blischak JD, Davenport ER, Wilson G (2016) A Quick Introduction to Version Control with Git and GitHub. PLOS Computational Biology 12(1): e1004668. https://doi.org/10.1371/journal.pcbi.1004668

### Teaching Material

Slides can be viewed at https://oxfordihtm.github.io/open-reproducible-science/session2.html

PDF version of slides can be downloaded at https://oxfordihtm.github.io/open-reproducible-science/pdf/session2-git-and-github-with-r.pdf

R scripts for slides available [here](https://github.com/OxfordIHTM/open-reproducible-science/blob/a0a2d152e62a06a9cab6995f219018e3c0aafc91/session2.Rmd)

<!---

## Session 3: Data extraction, transformation, and loading in R

### Further Reading

Practical R for Epidemiologists - https://practical-r.org

### Teaching Material

Slides can be viewed at https://oxfordihtm.github.io/open-reproducible-science/session3.html

PDF version of slides can be downloaded at https://oxfordihtm.github.io/open-reproducible-science/pdf/session3-working-with-data.pdf

R scripts for slides available at https://github.com/OxfordIHTM/open-reproducible-science/session3.Rmd


<br/>

## Session 4: Reproducible scientific workflows in R

### Further Reading

Dynamic Function-Oriented Make-Like Declarative Workflows - https://docs.ropensci.org/targets/

The targets R Package User Manual - https://books.ropensci.org/targets/

### Teaching Material

Slides can be viewed at https://oxfordihtm.github.io/open-reproducible-science/session4.html

PDF version of slides can be downloaded at https://oxfordihtm.github.io/open-reproducible-science/pdf/session4-reproducible-scientific-workflows.pdf

R scripts for slides available at https://github.com/OxfordIHTM/open-reproducible-science/session4.Rmd


<br/>

## Session 5: Making your R-based research project portable

### Further Reading

Introduction to renv - https://rstudio.github.io/renv/articles/renv.html

### Teaching Material

Slides can be viewed at https://oxfordihtm.github.io/open-reproducible-science/session5.html

PDF version of slides can be downloaded at https://oxfordihtm.github.io/open-reproducible-science/pdf/session4-portable-r-projects.pdf

R scripts for slides available at https://github.com/OxfordIHTM/open-reproducible-science/session5.Rmd


<br/>

## Session 6: Automating your R-based research project

### Further Reading

Understanding GitHub Actions - https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions

### Teaching Material

Slides can be viewed at https://oxfordihtm.github.io/open-reproducible-science/session6html

PDF version of slides can be downloaded at https://oxfordihtm.github.io/open-reproducible-science/pdf/session4-automating-workflows.pdf

R scripts for slides available at https://github.com/OxfordIHTM/open-reproducible-science/session6.Rmd
--->

## Series Lecturer

[Ernest Guevarra](https://ernest.guevarra.io)

## License

This work is licensed under a [GNU General Public License 3 (GPL-3)](https://github.com/OxfordIHTM/open-reproducible-science/blob/main/LICENSE.md).

