on:
  workflow_dispatch:
  push:
    branches: main

name: Publish slides

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:4.4.1
    permissions:
      contents: write
      id-token: write
      pages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          chromium-browser
                  
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render slides and PDFs
        run: |
          source("_render_slides.R")
        shell: Rscript {0}
        
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
        
      - name: Deploy to gh-pages
        uses: actions/deploy-pages@v4
        