on:
  pull_request:
    branches: main

name: Test render slides

jobs:
  test-render-slides:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:4.4.1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN  }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          curl

      - name: Install chrome
        run: |
          curl -LO https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          apt-get install -y ./google-chrome-stable_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb
                  
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render slides and PDFs
        run: |
          source("_render_slides.R")
        shell: Rscript {0}
        
      - name: Upload render outputs
        uses: actions/upload-artifact@v4
        with:
          path: docs
        